ARCH = 			$(shell arch)
USER = 			$(shell whoami)

CXX = 			g++
CXXFLAGS = 		-pthread -Wall

DEPS_DIR = 		$(TOP_BUILD_DIR)/deps
INCLUDES_DIR = 	$(DEPS_DIR)/headers
LIBS_DIR = 		$(DEPS_DIR)/libs/$(ARCH)

INCLUDES = 		-I $(INCLUDES_DIR) \

LIBS =			-L $(LIBS_DIR) \
				-lplankton \
				-lsched \
				-lboinc_crypt \
				-lboinc_api \
				-lboinc \
				-ltomcrypt \

SERVER_PATH = boincadm@172.20.175.53

ifeq ($(USER),frosty)
    SERVER_REPO = build/boinc
else
    SERVER_REPO = b_repo
endif
